version: "3.8"
services:
  db:
    image: mysql:latest
    networks:
      - backend
    ports:
      - 3306:3306
    volumes:
      - /home/shiraaz/data/mysql:/var/lib/mysql 
    environment:
      MYSQL_DATABASE: foremexplorer
      MYSQL_USER: foremexplorer
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password

networks:
  backend:
  